[package]
name = "adder-debug"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2018"
publish = false

[dependencies.adder]
path = ".."

[dependencies.dharitri-wasm-debug]
version = "0.0.2"
path = "../../../../dharitri-wasm-debug"
